#!/usr/bin/env perl
use strict;
use warnings;

$| = 1;

print "\n" x 10;

my %digits = (' ' => ['    ',
                      '    ',
                      '    ',
                      '    ',
                      '    '],
              '0' => [' ## ',
                      '#  #',
                      '#  #',
                      '#  #',
                      ' ## '],
              '1' => ['  # ',
                      ' ## ',
                      '  # ',
                      '  # ',
                      '  # '],
              '2' => ['### ',
                      '   #',
                      '  # ',
                      ' #  ',
                      '####'],
              '3' => ['### ',
                      '   #',
                      ' ## ',
                      '   #',
                      '### '],
              '4' => ['#  #',
                      '#  #',
                      '####',
                      '   #',
                      '   #'],
              '5' => ['####',
                      '#   ',
                      '### ',
                      '   #',
                      '### '],
              '6' => [' ###',
                      '#   ',
                      '### ',
                      '#  #',
                      ' ## '],
              '7' => ['####',
                      '   #',
                      '  # ',
                      ' #  ',
                      ' #  '],
              '8' => [' ## ',
                      '#  #',
                      ' ## ',
                      '#  #',
                      ' ## '],
              '9' => [' ## ',
                      '#  #',
                      ' ###',
                      '   #',
                      ' ## ']
             );

my @colon = (' ','#',' ','#',' ');
           




#my @spinbits = (' |', ' /', '---', ' \\');
#my $sec_counter = 0;
while (1) {
   my ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime(time);
   $hour = $hour > 12 ? $hour - 12 : $hour;

   my ($hr1, $hr2) = split(//, sprintf('%2d', $hour) );
   my ($mn1, $mn2) = split(//, sprintf('%02d', $min ) );
   print `clear`, "\n" x 55;
   #print "\n\nhr1=$hr1, hr2=$hr2, mn1=$mn1, mn2=$mn2\n\n";
   for my $line (0..4) {
      print $digits{$hr1}[$line], '  ',
            $digits{$hr2}[$line], '  ',
            $colon[$line],        '  ',
            $digits{$mn1}[$line], '  ',
            $digits{$mn2}[$line],
            "\n";
   }

   my $oldmin = $min;
   my $sec_counter = 0;
   while ($oldmin == $min) {
      #$sec_counter = ++$sec_counter %4;
      ++$sec_counter;
      my $chr = $sec_counter % 2 ? '/\\' : '__';
      print "\r" . ' ' x int($sec_counter / 2) . $chr . ' ' x (80 - int($sec_counter/2));
      #print "\r", ' ' x 28, $spinbits[$sec_counter], " " x 80;
      sleep 1;
      ($sec,$min) = localtime(time);
   }
}
