#!/usr/bin/env perl
use strict;
use warnings;

$| = 1;

print "\n" x 10;

my @spinbits = qw" | / - \ ";
my $spincounter = 0;
while (1) {
   my ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime(time);
   $hour = $hour > 12 ? $hour - 12 : $hour;
   $spincounter = ++$spincounter %4;
   printf "\r%2.d:%02d  %s%s", $hour, $min, $spinbits[$spincounter], " " x 80;
   sleep 1;
}
