#!/usr/bin/env bash

pr -2 -t <<'EOF'
COMMANDS
git status
git pull
git push
git fetch
git checkout
git branch
git merge
git rebase
git stash
git log
git diff
git show

CONFIG
user.name
user.email
core.editor
pull.rebase
push.default
color.ui
init.defaultBranch
fetch.prune
EOF

