#!/usr/bin/env perl
use strict;
use warnings;

my $module = shift or die "Usage: $0 Module::Name\n";

(my $file = $module) =~ s{::}{/}g;
$file .= '.pm';

eval "require $module" or die "Cannot load $module: $@\n";

print $INC{$file}, "\n";

