package dv_gdrive;

use v5.38;
use feature 'class';
no warnings 'experimental::class';

use LWP::UserAgent;
use HTTP::Request;
use Crypt::JWT qw(encode_jwt);

###########################################################################
###########################################################################
class dv_google {
###########################################################################
###########################################################################

use JSON;
use URI::Escape qw(uri_escape);

=pod

=head2 new()

Constructor (auto-generated by the C<class> system).

Example:

   use dv_google;

   my $ggl = dv_google->new(
                client_secret_path => "/home/dvergin/.credentials/google_client_secret.json",
                token_store_path   => "/home/dvergin/.credentials/google_token_store.json",
             );

=cut

   field $token_store_path   :param;
   field $client_secret_path :param;

###########################################################################
method _load_access_json () {
###########################################################################
   open my $fh, '<', $client_secret_path
      or die "Cannot open client_secret_path '$client_secret_path': $!";

   return decode_json(do { local $/; <$fh> });
}

###########################################################################
method get_access_token () {
###########################################################################
=pod

=head2 get_access_token()

Return a valid OAuth access token using the stored refresh token.

=cut

   my $oauth_client = $client_secret_path;
   my $token_file   = $token_store_path;

   open my $fh1, '<', $oauth_client
       or die "Cannot open $oauth_client: $!";
   my $client = decode_json(do { local $/; <$fh1> });

   open my $fh2, '<', $token_file
      or die "Cannot open $token_file: $!";
   my $tokens = decode_json(do { local $/; <$fh2> });

   my $client_id     = $client->{installed}{client_id}
                    || $client->{web}{client_id};
   my $client_secret = $client->{installed}{client_secret}
                    || $client->{web}{client_secret};

   my $refresh_token = $tokens->{refresh_token}
       or die "No refresh_token in token file";

   my $ua = LWP::UserAgent->new;
   my $res = $ua->post("https://oauth2.googleapis.com/token",
                 { client_id     => $client_id,
                   client_secret => $client_secret,
                   refresh_token => $refresh_token,
                   grant_type    => "refresh_token",
                 });

   die "Token refresh failed: "
       . $res->status_line . "\n"
       . $res->decoded_content
   unless $res->is_success;

   my $data = decode_json($res->decoded_content);
   return $data->{access_token};
}

###########################################################################
method http_get ($url, %opts) {
###########################################################################
=pod

=head2 http_get($url, %opts)

Perform an authenticated HTTP GET request.

Currently supported option:

    headers => { ... }

Returns the L<HTTP::Response> object.

=cut

   my $token = $self->get_access_token;
   my $req   = HTTP::Request->new(GET => $url);
   $req->header(Authorization => "Bearer $token");
   if (my $headers = $opts{headers}) {
      for my $name (sort keys %$headers) {
         $req->header($name => $headers->{$name});
      }
   }
   my $ua = LWP::UserAgent->new;
   return $ua->request($req);
}

###########################################################################
method gdrive_get_name_by_id ($file_id) {
###########################################################################
   my $url = "https://www.googleapis.com/drive/v3/files/$file_id"
           . "?fields=name";

   my $res = $self->http_get($url);

   die "Drive get request failed: " . $res->status_line . "\n" . $res->decoded_content
      unless $res->is_success;

   my $data = decode_json($res->decoded_content);

   return $data->{name};
}

###########################################################################
method gdrive_get_ids_by_name ($name_frag) {
###########################################################################
   my $q = uri_escape("name contains '$name_frag'");

   my $url = "https://www.googleapis.com/drive/v3/files"
           . "?q=$q"
           . "&fields=files(id,name)";

   my $res = $self->http_get($url);

   die "Drive search request failed: " . $res->status_line . "\n" . $res->decoded_content
      unless $res->is_success;

   my $data = decode_json($res->decoded_content);

   return [ map { $_->{id} } @{ $data->{files} // [] } ];
}

###########################################################################
#method gdrive_list_files ($folder_id  = "1Cryh79nUDRdkIy0_sYbsZwMby8kmtrkq") {
method gdrive_list_files ($folder_id  = "root") {
###########################################################################
=pod

=head2 gdrive_list_files()

$ggl->gdrive_list_files();            # lists a default directory
$ggl->gdrive_list_files($folder_id);  # lists contents of id'ed folder
      Returns a reference to an aoh describing the 
      files in the configured Google Drive folder.

Each returned element contains at least:

    id
    name

=cut

   my $url = "https://www.googleapis.com/drive/v3/files"
           . "?q='$folder_id'+in+parents"
           . "&fields=files(id,name)";

   my $res = $self->http_get($url);

   die "Drive list request failed: " . $res->status_line . "\n" . $res->decoded_content
      unless $res->is_success;

   my $data = decode_json($res->decoded_content);
   return $data->{files};
}

###########################################################################
method gdrive_get_file ($file_id) {
###########################################################################
=pod

=head2 gdrive_get_file($file_id)

Return the content of the specified Google Drive file.

=cut

   my $url = "https://www.googleapis.com/drive/v3/files/$file_id" . "?alt=media";
   my $res = $self->http_get($url);

   die "Drive get request failed: " . $res->status_line . "\n" . $res->decoded_content
      unless $res->is_success;

   return $res->decoded_content;
}

###########################################################################
method http_delete ($url, %opts) {
###########################################################################
=pod

=head2 http_delete($url, %opts)

Perform an authenticated HTTP DELETE request.

Currently supported option:

    headers => { ... }

Returns the L<HTTP::Response> object.

=cut

   my $token = $self->get_access_token;
   my $req   = HTTP::Request->new(DELETE => $url);
   $req->header(Authorization => "Bearer $token");

   if (my $headers = $opts{headers}) {
      for my $name (sort keys %$headers) {
         $req->header($name => $headers->{$name});
      }
   }
   my $ua = LWP::UserAgent->new;
   return $ua->request($req);
}

###########################################################################
method gdrive_delete_file ($file_id) {
###########################################################################
=pod

=head2 delete_file($file_id)

Delete the specified Google Drive file.

=cut

   my $url = "https://www.googleapis.com/drive/v3/files/$file_id";
   my $res = $self->http_delete($url);
   die "Drive delete request failed: " . $res->status_line . "\n" . $res->decoded_content
      unless $res->is_success;
   return 1;
}

###########################################################################
method http_post ($url, %opts) {
###########################################################################
=pod

=head2 http_post($url, %opts)

Perform an authenticated HTTP POST request.

Options:

    headers => { ... }
    content => $string

Returns the L<HTTP::Response> object.

=cut

   my $token = $self->get_access_token;
   my $req   = HTTP::Request->new(POST => $url);

   $req->header(Authorization => "Bearer $token");

   if (my $headers = $opts{headers}) {
      for my $name (sort keys %$headers) {
         $req->header($name => $headers->{$name});
      }
   }

   if (exists $opts{content}) {
      $req->content($opts{content});
   }

   my $ua = LWP::UserAgent->new;
   return $ua->request($req);
}

###########################################################################
method gdrive_put_file ($folder_id, $name, $content) {
###########################################################################
=pod

=head2 gdrive_put_file($name, $content)

Create a file in the configured Google Drive folder.

Arguments:

    $folder_id folder ID
    $name      file name
    $content   file content

Returns the file ID of the created file.

=cut

   my $meta = encode_json({name => $name, parents => [ $folder_id ], });

   my $boundary = "dv_gdrive_" . time;

   my $body = "--$boundary\r\n"
            . "Content-Type: application/json; charset=UTF-8\r\n\r\n"
            . $meta . "\r\n"
            . "--$boundary\r\n"
            . "Content-Type: text/plain\r\n\r\n"
            . $content . "\r\n"
            . "--$boundary--\r\n";

   my $url = "https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart";

   my $res = $self->http_post($url,
                              headers => {"Content-Type" => "multipart/related; boundary=$boundary"},
                              content => $body,
                             );

   die "Drive upload request failed: " . $res->status_line . "\n" . $res->decoded_content
       unless $res->is_success;

   my $data = decode_json($res->decoded_content);
   return $data->{id};
}

###########################################################################
method gtask_get_tasklists () {
###########################################################################
=pod

=head2 gtask_get_tasklists

  my $lists = $self->gtask_get_tasklists();

Return an arrayref of tasklists available to the authorized user.
Each element is a hashref as returned by the Google Tasks API.

Dies on request failure.

=cut

   my $url = 'https://tasks.googleapis.com/tasks/v1/users/@me/lists';
   my $res = $self->http_get($url);
   die "GTasks get_tasklists failed: " . $res->status_line . "\n" . $res->decoded_content
      unless $res->is_success;
   my $data = decode_json($res->decoded_content);
   return $data->{items} // [];
}

###########################################################################
method gtask_get_tasks ($tasklist_id, %opts) {
###########################################################################
=pod

=head2 gtask_get_tasks

  my $tasks = $self->gtask_get_tasks($tasklist_id, %opts);

Return an arrayref of tasks in the specified tasklist.

Optional %opts are passed as query parameters (e.g. showCompleted => 'true').

Dies on request failure.

=cut

   my @params;

   while (my ($k, $v) = each %opts) {
      push @params, uri_escape($k) . "=" . uri_escape($v);
   }

   my $qs  = @params ? "?" . join("&", @params) : "";
   my $url = "https://tasks.googleapis.com/tasks/v1/lists/$tasklist_id/tasks$qs";

   my $res = $self->http_get($url);

   die "GTasks get_tasks failed: " . $res->status_line . "\n" . $res->decoded_content
      unless $res->is_success;

   my $data = decode_json($res->decoded_content);

   return $data->{items} // [];
}

###########################################################################
method gtask_delete_task ($tasklist_id, $task_id) {
###########################################################################
=pod

=head2 gtask_delete_task

  $self->gtask_delete_task($tasklist_id, $task_id);

Delete the specified task from the given tasklist.

Returns true on success.

Dies on request failure.

=cut

   my $url = "https://tasks.googleapis.com/tasks/v1/lists/$tasklist_id/tasks/$task_id";

   my $res = $self->http_delete($url);

   die "GTasks delete_task failed: " . $res->status_line . "\n" . $res->decoded_content
      unless $res->is_success;

   return 1;
}

###########################################################################
} ## END OF CLASS
###########################################################################

1;

