package dv_gdrive;

use v5.38;
use feature 'class';
no warnings 'experimental::class';

use JSON;
use LWP::UserAgent;
use HTTP::Request;
use Crypt::JWT qw(encode_jwt);
use URI::Escape qw(uri_escape);

class dv_gdrive {

=pod

=head2 new()

Constructor (auto-generated by the C<class> system).

Example:

    use dv_gdrive;

    my $gdrive = dv_gdrive->new(
        access_json_path => "$ENV{HOME}/.credentials/gdrive-access-489406-7e42133786c7.json",
        folder_id        => "1Cryh79nUDRdkIy0_sYbsZwMby8kmtrkq",
    );

Remember to share the target Google Drive folder with the service
account email as Editor.

=cut

    field $token_json_path   :param;
    field $access_json_path  :param;
    field $folder_id         :param;

    method access_json_path () {
=pod

=head2 access_json_path()

Return the path to the JSON credential file.

=cut

        return $access_json_path;
    }

    method token_json_path () {
=pod

=head2 token_json_path()

Return the path to the OAuth user token JSON file.

=cut

        return $token_json_path;
    }

    method folder_id () {
=pod

=head2 folder_id()

Return the configured Google Drive folder ID.

=cut

        return $folder_id;
    }

    method _load_access_json () {
        open my $fh, '<', $access_json_path
            or die "Cannot open access_json_path '$access_json_path': $!";

        return decode_json(do { local $/; <$fh> });
    }

    method get_access_token () {
=pod

=head2 get_access_token()

Return a valid OAuth access token using the stored refresh token.

=cut

        my $oauth_client = $access_json_path;
        my $token_file   = $token_json_path;

        open my $fh1, '<', $oauth_client
            or die "Cannot open $oauth_client: $!";
        my $client = decode_json(do { local $/; <$fh1> });

        open my $fh2, '<', $token_file
            or die "Cannot open $token_file: $!";
        my $tokens = decode_json(do { local $/; <$fh2> });

        my $client_id =
               $client->{installed}{client_id}
            || $client->{web}{client_id};

        my $client_secret =
               $client->{installed}{client_secret}
            || $client->{web}{client_secret};

        my $refresh_token = $tokens->{refresh_token}
            or die "No refresh_token in token file";

        my $ua = LWP::UserAgent->new;

        my $res = $ua->post(
            "https://oauth2.googleapis.com/token",
            {
                client_id     => $client_id,
                client_secret => $client_secret,
                refresh_token => $refresh_token,
                grant_type    => "refresh_token",
            }
        );

        die "Token refresh failed: "
            . $res->status_line . "\n"
            . $res->decoded_content
            unless $res->is_success;

        my $data = decode_json($res->decoded_content);

        return $data->{access_token};
    }



    method http_get ($url, %opts) {
=pod

=head2 http_get($url, %opts)

Perform an authenticated HTTP GET request.

Currently supported option:

    headers => { ... }

Returns the L<HTTP::Response> object.

=cut

        my $token = $self->get_access_token;
        my $req   = HTTP::Request->new(GET => $url);

        $req->header(Authorization => "Bearer $token");

        if (my $headers = $opts{headers}) {
            for my $name (sort keys %$headers) {
                $req->header($name => $headers->{$name});
            }
        }

        my $ua = LWP::UserAgent->new;
        return $ua->request($req);
    }

    method list_files () {
=pod

=head2 list_files()

Return a Perl data structure describing the files in the configured
Google Drive folder.

Each element contains at least:

    id
    name

=cut

        my $url =
            "https://www.googleapis.com/drive/v3/files"
          . "?q='$folder_id'+in+parents"
          . "&fields=files(id,name)";

        my $res = $self->http_get($url);

        die "Drive list request failed: " . $res->status_line . "\n" . $res->decoded_content
            unless $res->is_success;

        my $data = decode_json($res->decoded_content);

        return $data->{files};
    }

    method get_file ($file_id) {
=pod

=head2 get_file($file_id)

Return the content of the specified Google Drive file.

=cut

        my $url =
            "https://www.googleapis.com/drive/v3/files/$file_id"
          . "?alt=media";

        my $res = $self->http_get($url);

        die "Drive get request failed: " . $res->status_line . "\n" . $res->decoded_content
            unless $res->is_success;

        return $res->decoded_content;
    }

    method http_delete ($url, %opts) {
=pod

=head2 http_delete($url, %opts)

Perform an authenticated HTTP DELETE request.

Currently supported option:

    headers => { ... }

Returns the L<HTTP::Response> object.

=cut

        my $token = $self->get_access_token;
        my $req   = HTTP::Request->new(DELETE => $url);

        $req->header(Authorization => "Bearer $token");

        if (my $headers = $opts{headers}) {
            for my $name (sort keys %$headers) {
                $req->header($name => $headers->{$name});
            }
        }

        my $ua = LWP::UserAgent->new;
        return $ua->request($req);
    }

    method delete_file ($file_id) {
=pod

=head2 delete_file($file_id)

Delete the specified Google Drive file.

=cut

        my $url = "https://www.googleapis.com/drive/v3/files/$file_id";

        my $res = $self->http_delete($url);

        die "Drive delete request failed: " . $res->status_line . "\n" . $res->decoded_content
            unless $res->is_success;

        return 1;
    }

    method http_post ($url, %opts) {
=pod

=head2 http_post($url, %opts)

Perform an authenticated HTTP POST request.

Options:

    headers => { ... }
    content => $string

Returns the L<HTTP::Response> object.

=cut

        my $token = $self->get_access_token;
        my $req   = HTTP::Request->new(POST => $url);

        $req->header(Authorization => "Bearer $token");

        if (my $headers = $opts{headers}) {
            for my $name (sort keys %$headers) {
                $req->header($name => $headers->{$name});
            }
        }

        if (exists $opts{content}) {
            $req->content($opts{content});
        }

        my $ua = LWP::UserAgent->new;
        return $ua->request($req);
    }

    method put_file ($name, $content) {
=pod

=head2 put_file($name, $content)

Create a file in the configured Google Drive folder.

Arguments:

    $name     file name
    $content  file content

Returns the file ID of the created file.

=cut

        my $meta = encode_json({
            name    => $name,
            parents => [ $folder_id ],
        });

        my $boundary = "dv_gdrive_" . time;

        my $body =
            "--$boundary\r\n"
          . "Content-Type: application/json; charset=UTF-8\r\n\r\n"
          . $meta . "\r\n"
          . "--$boundary\r\n"
          . "Content-Type: text/plain\r\n\r\n"
          . $content . "\r\n"
          . "--$boundary--\r\n";

        my $url = "https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart";

        my $res = $self->http_post(
            $url,
            headers => {
                "Content-Type" => "multipart/related; boundary=$boundary"
            },
            content => $body,
        );

        die "Drive upload request failed: "
            . $res->status_line . "\n" . $res->decoded_content
            unless $res->is_success;

        my $data = decode_json($res->decoded_content);

        return $data->{id};
    }

}

1;

